### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by akande085** [haqq-network/haqq#163]
*I sent 3000 Islamic coin free from trust wallet but for the past one hour it has not arrived in my Haqq wallet please help me.*

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.2.1-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Changwey** [comment]
0x5ee159c6239b5ce5e1eebd1ce49fb65a0212c52c

Sorry please can you send me some if you have got it back thanks very much.

Allah bless you if you Muslim and guide you if you are not.
