### ISSUE TITLE
I need help asap I'm sick of trying to get through to you because of your wallet that doesn't work I have lost a lot of money I'm so disappointed HAQQ wallet is probably nothing but a scam if nobody reaches out to me to fix this issue that means you don't care about your clients and all this talk about shreia law is nothing but cosmetic I really believed in you and you have let me down what a shame it was to good to be true finally a Islamic wallet I was so happy only to be let down miserably

### ISSUE THREAD

**Issue by Alsol123j** [haqq-network/haqq#168]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

__Steps to reproduce:__

1. [First Step]
2. [Second Step]
3. [and so on...]

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by Alsol123j** [comment]
I am so disappointed with HAQQ wallet so upset you can't get through to customer support I've lost a lot of money because the HAQQ wallet doesn't even work

**Comment by Ashok1927** [comment]
So Sorry,
I support you any time

**Comment by Ashok1927** [comment]
My HAQQ TOKEN NOT RECIBE TO TILL.

**Comment by Yabagi** [comment]
You're so stupid! Did any HAQQ member ask you to give money?

**Comment by Ashok1927** [comment]
I don't like any "antiphising code" mail for derivation.😢
Please Don't send me your "antiphising code" mail😢
Please stop your "mail"

I like only True official website mail only.😢

I am informing you... I like only true officiel mail.
I like mail only... 👌

AshokDubey

**Comment by Alsol123j** [comment]
Who is calling me stupid and for what reason. I'm complaining about my HAQQ wallet not working properly and I've lost money because of this issue and I've been trying to get through to customer support and they don't even answer what am I supposed to do I've tried every single Chanel and not one reply and someone is calling me stupid

**Comment by Yurist-85** [comment]
Hello,

Nobody from HAQQ team will ever ask you to send money, a mnemonic phrase, or a private key.
