### ISSUE TITLE
Failed  transaction 

### ISSUE THREAD

**Issue by Abakwaboy** [haqq-network/haqq#177]
*Describe your issue here.*

Failed  transaction. I made a transaction a few days ago but didn't receive the coins in the receivers account.  Below is the transaction hash. Please help me get the coins. thanks 
0xc02f20991607e5e37f9f2a7074ed4116a83f7d35efc8709037e328db429b2469

**Comment by Yurist-85** [comment]
Hello,

There are no transactions with a given TX hash both mainnet and testnet.
