### ISSUE TITLE
Mainnet: <Issue Title> mistakenly send 0.01 ISLM COIN to this wallet address (0x16B0bb31ACC31f07d9C7B9178a6ee5Da0d3B338C)

### ISSUE THREAD

**Issue by Tijani28** [haqq-network/haqq#180]
*Describe your issue here.*

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.2.1-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*mistakenly send 0.01 ISLM COIN to this wallet address ((0x16B0bb31ACC31f07d9C7B9178a6ee5Da0d3B338C)

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Yurist-85** [comment]
Unfortunately, we can't help. Blockchain transactions are final and can't be reverted.
