### ISSUE TITLE
Mainnet: <Issue Title>0x8DEdde3911A3e8b811e7eB6f331713b39E64BC5B

### ISSUE THREAD

**Issue by Ubamusa** [haqq-network/haqq#184]
I didn't receive my coin but it's show's transaction successful

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.2.1-beta

* User Agent: `Mozilla/5.0 (Linux; Android 13; Infinix X678B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Yurist-85** [comment]
Hello. If you meant the following transfer:
https://explorer.haqq.network/tx/0x94cb7d2c3c8faaa415f5ecee72a0154282c39c92d2bdd277738fdc41b0504c0e

then all transferred coins are on your account
https://explorer.haqq.network/address/0x8DEdde3911A3e8b811e7eB6f331713b39E64BC5B
