### ISSUE TITLE
Mainnet: <Issue Tithale>hackeo de wallet 

### ISSUE THREAD

**Issue by Kushami1** [haqq-network/haqq#186]
*Describe your issue here.*
Hello, I hope you are well, they tried to hack my wallet yesterday once and today 4 times, what should I do to protect my wallet?
### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.2.1-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by Kushami1** [comment]
Hello, I hope you are well, they tried to hack my wallet yesterday once and today 4 times, what should I do to protect my wallet?

**Comment by Kushami1** [comment]
![Screenshot_2023-08-20-09-24-59-403_com haqq wallet](https://github.com/haqq-network/haqq/assets/140758241/1790a61a-b8fe-4fd0-931a-39de7993d4c2)

**Comment by Yurist-85** [comment]
Hello,

Don't worry, nobody wants to hack your account. All outbound transactions mentioned above are smart-contract interactions initiated when you request raffle tickets.
