### ISSUE TITLE
Mainnet: <Issue Title>

### ISSUE THREAD

**Issue by needles777** [haqq-network/haqq#190]
0x7d73409c5b83bdda2f07f467a49c11b9d1f74bb1

I have Futura and hcwa but why not show in my wallet
![Uploading Screenshot_20230827_133027.jpg…]()

**Comment by Yurist-85** [comment]
As I see, all the tokens mentioned above are on your account:
https://explorer.haqq.network/address/0x7d73409C5b83BdDa2F07F467a49C11B9d1F74bb1

They are not related to HAQQ Network and its native Islamic Coin though.
