### ISSUE TITLE
module structure standards guide is not accessible 

### ISSUE THREAD

**Issue by bug-author** [haqq-network/haqq#265]
__Steps to reproduce:__

1. Create a PR
2. Visit [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md) in the template under heading **For Contributors use**
3. Shows a 404 page

__Expected behavior:__ Should show the module structure standards for contributions

__Actual behavior:__ Shows a 404 page

<img width="1128" alt="image" src="https://github.com/haqq-network/haqq/assets/48406637/cc60b6b3-3b79-4662-a119-122d707c3c72">

**Comment by kioqq** [comment]
docs moved to https://github.com/haqq-network/docs
