### ISSUE TITLE
Mainnet: <Transaction issues>

### ISSUE THREAD

**Issue by Hyder21** [haqq-network/haqq#274]
*Describe your issue here.*
I have tried lot of times to send my ISLM COIN to okx and ku coin but couldn't receive over here.
### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: v5.2.1-beta

* User Agent: `Mozilla/5.0 (Linux; Android 10; itel L6006 Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.144 Mobile Safari/537.36 AgentWeb/1.0  UCBrowser/11.6.4.950`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by onsails** [comment]
Please send CEX deposit issues to CEXes support teams.
