### ISSUE TITLE
Rosetta API server fail to start

### ISSUE THREAD

**Issue by colossus-digital** [haqq-network/haqq#278]
Hi guys, i'm trying to enable the node's internal Rosetta API server but, when enabled in the app.toml the node fails to start with the error:

`Error: rosetta: (500) internal error`

This is the Rosetta configuration:

```
###############################################################################
###                           Rosetta Configuration                         ###
###############################################################################

[rosetta]

# Enable defines if the Rosetta API server should be enabled.
enable = true

# Address defines the Rosetta API server to listen on.
address = "0.0.0.0:8080"

# Network defines the name of the blockchain that will be returned by Rosetta.
blockchain = "haqq"

# Network defines the name of the network that will be returned by Rosetta.
network = "haqq_11235-1"

# Retries defines the number of retries when connecting to the node before failing.
retries = 3

# Offline defines if Rosetta server should run in offline mode.
offline = false

# EnableDefaultSuggestedFee defines if the server should suggest fee by default.
# If 'construction/medata' is called without gas limit and gas price,
# suggested fee based on gas-to-suggest and denom-to-suggest will be given.
enable-fee-suggestion = false

# GasToSuggest defines gas limit when calculating the fee
gas-to-suggest = 200000

# DenomToSuggest defines the defult denom for fee suggestion.
# Price must be in minimum-gas-prices.
denom-to-suggest = "aISLM"
```

Any idea ?

**Comment by Yurist-85** [comment]
We are going to upgrade to SDK v0.50 soon.

According to Cosmos SDK [documentation](https://docs.cosmos.network/v0.50/build/migrations/upgrading#tooling):

> Rosetta has moved to its own repo and not imported by the Cosmos SDK SimApp by default. Any user who is interested on using the tool can connect it standalone to any node without the need to add it as part of the node binary.
> 
> The rosetta tool also allows multi chain connections.

After upgrade we'll find out how to run Rosetta with our node and run it.

**Comment by colossus-digital** [comment]
great thanks
btw, i tried also with the standalone version [here:](https://github.com/cosmos/rosetta) but it doesn't work too 

![image](https://github.com/haqq-network/haqq/assets/104019153/5aadf844-0649-430a-b939-c6ac016a4cd4)
