### ISSUE TITLE
Fix total supply

### ISSUE THREAD

**Issue by onsails** [haqq-network/haqq#4]
During preparations for #3 rollout we've been submitted a Proposal №1 which has failed due to voting process failure. This has led to burning of 70M aISLM.
To fix total supply, #3 should be appended by minting missing 70M aISLM to evergreen pool.

**Total Supply Change**
```
before prop 1:  20000000000000000000000000000 aISLM (20 000 000 000 ISLM)
after prop 1:   19999999999999999999930000000 aISLM (19 999 999 999. 999 999 999 93 ISLM)
<-- we are here
after fix:      20000000000000000000000000000 aISLM (20 000 000 000 ISLM)
```

**Comment by kioqq** [comment]
fixed by: https://github.com/haqq-network/haqq/pull/3 https://github.com/haqq-network/haqq/pull/8
with upgrade mainnet to: v1.0.2
